// Generated by CoffeeScript 1.8.0
var Gofer, Singularity, version,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Gofer = require('gofer');

version = require('../package.json').version;

Singularity = (function(_super) {
  __extends(Singularity, _super);

  function Singularity() {
    return Singularity.__super__.constructor.apply(this, arguments);
  }

  Singularity.prototype.serviceName = 'singularity';

  Singularity.prototype.serviceVersion = version;

  return Singularity;

})(Gofer);

Singularity.prototype.clearOptionMappers();

Singularity.prototype.addOptionMapper(function(opts) {
  return this.applyBaseUrl("" + opts.baseUrl + "/api", opts);
});

Singularity.prototype.registerEndpoints({
  requests: require('./endpoints/requests'),
  webhooks: require('./endpoints/webhooks')
});

module.exports = Singularity;
