// Generated by CoffeeScript 1.9.0
module.exports = function(request) {
  return {
    create: function(deploy, user, cb) {
      if (!cb) {
        cb = user;
        user = void 0;
      }
      return request('/deploys', {
        method: 'POST',
        json: {
          deploy: deploy
        }
      }, cb);
    },
    "delete": function(deployId, requestId, user, cb) {
      if (!cb) {
        cb = user;
        user = void 0;
      }
      return request('/deploys/deploy/{deployId}/request/{requestId}', {
        method: 'DELETE',
        pathParams: {
          deployId: deployId,
          requestId: requestId
        },
        qs: {
          user: user
        }
      }, cb);
    },
    pending: function(cb) {
      return request('/deploys/pending', {
        method: 'GET'
      }, cb);
    }
  };
};
