// Generated by CoffeeScript 1.9.0
module.exports = function(request) {
  return {
    task: function(taskId, cb) {
      return request("/history/task/" + taskId, {
        method: 'GET'
      }, cb);
    }
  };
};
