// Generated by CoffeeScript 1.8.0
module.exports = function(request) {
  return {
    add: function(hook, uri, cb) {
      var payload;
      payload = {
        uri: "" + uri + "/" + hook,
        type: hook.toUpperCase()
      };
      return request('/webhooks', {
        method: 'POST',
        json: payload
      }, cb);
    },
    "delete": function(hook, uri, cb) {
      return request('/webhooks/{uri}', {
        method: 'DELETE',
        pathParams: {
          uri: "" + (hook.toUpperCase()) + "-" + uri + "/" + hook
        }
      }, cb);
    }
  };
};
